2023-04-10 15:40:47,931 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Configure stats pid to 7200
2023-04-10 15:40:47,931 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-10 15:40:47,931 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_154047-kyxz6r5f\logs\debug.log
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_154047-kyxz6r5f\logs\debug-internal.log
2023-04-10 15:40:47,932 INFO    MainThread:7200 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000021339C984F0>
2023-04-10 15:40:47,933 INFO    MainThread:7200 [wandb_init.py:init():546] calling init triggers
2023-04-10 15:40:47,933 INFO    MainThread:7200 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-10 15:40:47,933 INFO    MainThread:7200 [wandb_init.py:init():602] starting backend
2023-04-10 15:40:47,933 INFO    MainThread:7200 [wandb_init.py:init():606] setting up manager
2023-04-10 15:40:47,935 INFO    MainThread:7200 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-10 15:40:47,942 INFO    MainThread:7200 [wandb_init.py:init():613] backend started and connected
2023-04-10 15:40:47,949 INFO    MainThread:7200 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-10 15:40:47,951 INFO    MainThread:7200 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-10 15:40:47,951 INFO    MainThread:7200 [wandb_init.py:init():701] updated telemetry
2023-04-10 15:40:47,994 INFO    MainThread:7200 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-10 15:40:48,631 INFO    MainThread:7200 [wandb_run.py:_on_init():2133] communicating current version
2023-04-10 15:40:48,836 INFO    MainThread:7200 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-10 15:40:48,836 INFO    MainThread:7200 [wandb_init.py:init():789] starting run threads in backend
2023-04-10 15:40:49,041 INFO    MainThread:7200 [wandb_run.py:_console_start():2114] atexit reg
2023-04-10 15:40:49,041 INFO    MainThread:7200 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-10 15:40:49,041 INFO    MainThread:7200 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-10 15:40:49,041 INFO    MainThread:7200 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-10 15:40:49,041 INFO    MainThread:7200 [wandb_init.py:init():831] run started, returning control to user process
2023-04-10 15:40:49,042 INFO    MainThread:7200 [wandb_config.py:__setitem__():152] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002133A99ED40>>
2023-04-10 15:40:49,042 INFO    MainThread:7200 [wandb_run.py:_config_callback():1251] config_cb learning_rate 0.001 None
2023-04-10 15:40:49,042 INFO    MainThread:7200 [wandb_config.py:__setitem__():152] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002133A99ED40>>
2023-04-10 15:40:49,043 INFO    MainThread:7200 [wandb_run.py:_config_callback():1251] config_cb batch_size 32 None
2023-04-10 15:40:49,043 INFO    MainThread:7200 [wandb_config.py:__setitem__():152] config set epochs = 1 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002133A99ED40>>
2023-04-10 15:40:49,043 INFO    MainThread:7200 [wandb_run.py:_config_callback():1251] config_cb epochs 1 None
2023-04-10 15:41:41,371 INFO    MainThread:7200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 15:41:41,371 INFO    MainThread:7200 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-10 15:41:41,385 INFO    MainThread:7200 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-10 15:41:41,424 INFO    MainThread:7200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 15:41:41,424 INFO    MainThread:7200 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-10 15:41:41,433 INFO    MainThread:7200 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-10 15:41:41,571 INFO    MainThread:7200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 15:41:41,571 INFO    MainThread:7200 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-10 15:49:45,282 INFO    MainThread:7200 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-10 15:49:45,406 INFO    MainThread:7200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 15:49:45,406 INFO    MainThread:7200 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-10 15:49:48,340 INFO    MainThread:7200 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-10 15:49:48,358 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Configure stats pid to 7200
2023-04-10 15:49:48,358 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-10 15:49:48,358 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-10 15:49:48,358 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-10 15:49:48,358 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-10 15:49:48,359 INFO    MainThread:7200 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-10 15:49:48,359 INFO    MainThread:7200 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_154948-gwiyfjry\logs\debug.log
2023-04-10 15:49:48,359 INFO    MainThread:7200 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230410_154948-gwiyfjry\logs\debug-internal.log
2023-04-10 15:49:48,360 INFO    MainThread:7200 [wandb_init.py:init():546] calling init triggers
2023-04-10 15:49:48,360 INFO    MainThread:7200 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-10 15:49:48,360 INFO    MainThread:7200 [wandb_init.py:init():568] re-initializing run, found existing run on stack: kyxz6r5f
2023-04-10 15:49:48,361 INFO    MainThread:7200 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/kyxz6r5f
2023-04-10 15:49:48,362 INFO    MainThread:7200 [jupyter.py:save_history():445] not saving jupyter history
2023-04-10 15:49:48,362 INFO    MainThread:7200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-10 15:49:48,362 INFO    MainThread:7200 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-04-10 15:49:48,362 INFO    MainThread:7200 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-10 15:49:48,362 INFO    MainThread:7200 [wandb_run.py:_restore():2066] restore
2023-04-10 15:49:48,363 INFO    MainThread:7200 [wandb_run.py:_restore():2072] restore done
2023-04-10 15:52:19,839 WARNING MsgRouterThr:7200 [router.py:message_loop():77] message_loop has been closed
2023-04-10 15:52:20,763 INFO    MainThread:7200 [wandb_run.py:_restore():2066] restore
2023-04-10 15:52:20,763 INFO    MainThread:7200 [wandb_run.py:_restore():2072] restore done
2023-04-10 15:52:20,814 ERROR   MainThread:7200 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2092, in _atexit_cleanup
    self._on_finish()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2325, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2290, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 581, in init
    self._wl._global_run_stack[-1].finish()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1845, in finish
    return self._finish(exit_code, quiet)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1860, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2103, in _atexit_cleanup
    self._backend.cleanup()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\backend\backend.py", line 259, in cleanup
    self.interface.join()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 638, in join
    super().join()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\interface.py", line 741, in join
    _ = self._communicate_shutdown()
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 551, in _communicate_shutdown
    _ = self._communicate(record)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\interface\router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "d:\programs\pyhtonprograms\bettscrapper\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
