2023-04-12 15:22:50,834 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Configure stats pid to 15728
2023-04-12 15:22:50,834 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-12 15:22:50,834 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-12 15:22:50,835 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-12 15:22:50,835 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-12 15:22:50,835 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-12 15:22:50,835 INFO    MainThread:15728 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_152250-crjiahm9\logs\debug.log
2023-04-12 15:22:50,835 INFO    MainThread:15728 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_152250-crjiahm9\logs\debug-internal.log
2023-04-12 15:22:50,836 INFO    MainThread:15728 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000234E1E77520>
2023-04-12 15:22:50,836 INFO    MainThread:15728 [wandb_init.py:init():546] calling init triggers
2023-04-12 15:22:50,836 INFO    MainThread:15728 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-12 15:22:50,836 INFO    MainThread:15728 [wandb_init.py:init():568] re-initializing run, found existing run on stack: fp6gs1t5
2023-04-12 15:22:50,838 INFO    MainThread:15728 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/fp6gs1t5
2023-04-12 15:22:50,838 INFO    MainThread:15728 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-12 15:22:50,839 INFO    MainThread:15728 [wandb_run.py:_restore():2066] restore
2023-04-12 15:22:50,839 INFO    MainThread:15728 [wandb_run.py:_restore():2072] restore done
2023-04-12 15:23:01,526 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-04-12 15:23:01,527 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-04-12 15:23:01,534 INFO    MainThread:15728 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-04-12 15:23:01,540 INFO    MainThread:15728 [wandb_init.py:init():602] starting backend
2023-04-12 15:23:01,540 INFO    MainThread:15728 [wandb_init.py:init():606] setting up manager
2023-04-12 15:23:01,543 INFO    MainThread:15728 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-12 15:23:01,545 INFO    MainThread:15728 [wandb_init.py:init():613] backend started and connected
2023-04-12 15:23:01,552 INFO    MainThread:15728 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-12 15:23:01,552 INFO    MainThread:15728 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-12 15:23:01,552 INFO    MainThread:15728 [wandb_init.py:init():701] updated telemetry
2023-04-12 15:23:01,613 INFO    MainThread:15728 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-12 15:23:03,516 INFO    MainThread:15728 [wandb_run.py:_on_init():2133] communicating current version
2023-04-12 15:23:03,695 INFO    MainThread:15728 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-12 15:23:03,695 INFO    MainThread:15728 [wandb_init.py:init():789] starting run threads in backend
2023-04-12 15:23:03,859 INFO    MainThread:15728 [wandb_run.py:_console_start():2114] atexit reg
2023-04-12 15:23:03,859 INFO    MainThread:15728 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-12 15:23:03,859 INFO    MainThread:15728 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-12 15:23:03,859 INFO    MainThread:15728 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-12 15:23:03,860 INFO    MainThread:15728 [wandb_init.py:init():831] run started, returning control to user process
2023-04-12 15:23:03,860 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234E98ED960>>
2023-04-12 15:23:03,860 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb learning_rate 0.001 None
2023-04-12 15:23:03,861 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234E98ED960>>
2023-04-12 15:23:03,861 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb batch_size 32 None
2023-04-12 15:23:03,861 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set epochs = 20 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234E98ED960>>
2023-04-12 15:23:03,861 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb epochs 20 None
2023-04-12 16:05:06,745 INFO    MainThread:15728 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-12 16:05:06,745 INFO    MainThread:15728 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-12 16:05:06,763 INFO    MainThread:15728 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-12 16:05:06,803 INFO    MainThread:15728 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-12 16:05:06,803 INFO    MainThread:15728 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-12 16:05:06,811 INFO    MainThread:15728 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-12 16:05:06,933 INFO    MainThread:15728 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-12 16:05:06,933 INFO    MainThread:15728 [wandb_init.py:_pause_backend():417] pausing backend
2023-04-12 16:05:06,967 INFO    MainThread:15728 [wandb_init.py:_resume_backend():422] resuming backend
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Configure stats pid to 15728
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-12 16:05:06,981 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-12 16:05:06,982 INFO    MainThread:15728 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_160506-94xl8rgg\logs\debug.log
2023-04-12 16:05:06,982 INFO    MainThread:15728 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_160506-94xl8rgg\logs\debug-internal.log
2023-04-12 16:05:06,982 INFO    MainThread:15728 [wandb_init.py:init():546] calling init triggers
2023-04-12 16:05:06,983 INFO    MainThread:15728 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-12 16:05:06,983 INFO    MainThread:15728 [wandb_init.py:init():568] re-initializing run, found existing run on stack: crjiahm9
2023-04-12 16:05:06,985 INFO    MainThread:15728 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/crjiahm9
2023-04-12 16:05:06,986 INFO    MainThread:15728 [jupyter.py:save_history():445] not saving jupyter history
2023-04-12 16:05:06,986 INFO    MainThread:15728 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-12 16:05:06,986 INFO    MainThread:15728 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-04-12 16:05:06,986 INFO    MainThread:15728 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-12 16:05:06,987 INFO    MainThread:15728 [wandb_run.py:_restore():2066] restore
2023-04-12 16:05:06,987 INFO    MainThread:15728 [wandb_run.py:_restore():2072] restore done
2023-04-12 16:05:16,285 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-04-12 16:05:16,286 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-04-12 16:05:16,292 INFO    MainThread:15728 [wandb_run.py:_footer_sync_info():3380] logging synced files
