2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Configure stats pid to 15728
2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\andre\.config\wandb\settings
2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\settings
2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-12 22:37:21,319 INFO    MainThread:15728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:_log_setup():506] Logging user logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_223721-c9ddv95d\logs\debug.log
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:_log_setup():507] Logging internal logs to D:\10.semester\NN\neural-networks\2.zadanie\src\wandb\run-20230412_223721-c9ddv95d\logs\debug-internal.log
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000234E6FD9E10>
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:init():546] calling init triggers
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-04-12 22:37:21,320 INFO    MainThread:15728 [wandb_init.py:init():568] re-initializing run, found existing run on stack: vahfuawd
2023-04-12 22:37:21,322 INFO    MainThread:15728 [wandb_run.py:_finish():1854] finishing run neural-netwok-nn/neural-network-assgiment2/vahfuawd
2023-04-12 22:37:21,323 INFO    MainThread:15728 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-12 22:37:21,323 INFO    MainThread:15728 [wandb_run.py:_restore():2066] restore
2023-04-12 22:37:21,323 INFO    MainThread:15728 [wandb_run.py:_restore():2072] restore done
2023-04-12 22:37:43,907 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-04-12 22:37:43,907 INFO    MainThread:15728 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-04-12 22:37:43,914 INFO    MainThread:15728 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-04-12 22:37:43,919 INFO    MainThread:15728 [wandb_init.py:init():602] starting backend
2023-04-12 22:37:43,919 INFO    MainThread:15728 [wandb_init.py:init():606] setting up manager
2023-04-12 22:37:43,923 INFO    MainThread:15728 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-12 22:37:43,927 INFO    MainThread:15728 [wandb_init.py:init():613] backend started and connected
2023-04-12 22:37:43,933 INFO    MainThread:15728 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-12 22:37:43,933 INFO    MainThread:15728 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-12 22:37:43,934 INFO    MainThread:15728 [wandb_init.py:init():701] updated telemetry
2023-04-12 22:37:43,994 INFO    MainThread:15728 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-12 22:37:45,494 INFO    MainThread:15728 [wandb_run.py:_on_init():2133] communicating current version
2023-04-12 22:37:45,809 INFO    MainThread:15728 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-12 22:37:45,809 INFO    MainThread:15728 [wandb_init.py:init():789] starting run threads in backend
2023-04-12 22:37:45,980 INFO    MainThread:15728 [wandb_run.py:_console_start():2114] atexit reg
2023-04-12 22:37:45,980 INFO    MainThread:15728 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-12 22:37:45,980 INFO    MainThread:15728 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-12 22:37:45,981 INFO    MainThread:15728 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-12 22:37:45,981 INFO    MainThread:15728 [wandb_init.py:init():831] run started, returning control to user process
2023-04-12 22:37:45,981 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234EEF50520>>
2023-04-12 22:37:45,981 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb learning_rate 0.001 None
2023-04-12 22:37:45,982 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234EEF50520>>
2023-04-12 22:37:45,982 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb batch_size 32 None
2023-04-12 22:37:45,982 INFO    MainThread:15728 [wandb_config.py:__setitem__():152] config set epochs = 20 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000234EEF50520>>
2023-04-12 22:37:45,982 INFO    MainThread:15728 [wandb_run.py:_config_callback():1251] config_cb epochs 20 None
2023-04-12 22:39:45,036 WARNING MsgRouterThr:15728 [router.py:message_loop():77] message_loop has been closed
2023-04-12 22:39:45,057 INFO    MainThread:15728 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-12 22:39:45,057 INFO    MainThread:15728 [wandb_init.py:_pause_backend():417] pausing backend
